/**
 * Regenerates src/lib/icons.ts with only the icons the site uses.
 * Stroke icons: Lucide (ISC). Brand marks: Simple Icons (CC0).
 *   node scripts/build-icons.mjs
 */
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const lucide = require('lucide');
const simple = require('simple-icons');

const stroke = [
  'Phone',
  'MapPin',
  'Menu',
  'X',
  'ArrowRight',
  'ArrowUpRight',
  'ArrowLeft',
  'ChevronLeft',
  'ChevronRight',
  'ChevronDown',
  'ChevronUp',
  'Clock',
  'Star',
  'Check',
  'Plus',
  'Minus',
  'Search',
  'ShoppingBag',
  'Calendar',
  'Truck',
  'Store',
  'Mail',
  'Link',
  'Palette',
  'Languages',
  'Trash2',
  'Cake',
  'Gift',
  'Heart',
  'Gem',
  'PartyPopper',
  'Briefcase',
  'Baby',
  'Sparkles',
  'Info',
  'Navigation',
  'Copy',
  'CakeSlice',
  'Croissant',
  'Wheat',
  'EggOff',
  'Leaf',
  'Quote',
  'SlidersHorizontal',
  'Utensils',
  'ExternalLink',
  'Send',
  'MessageCircle',
  'Camera',
  'Cookie',
  'Coffee',
  'Ribbon',
  'Crown',
  'Flame',
  'Candy',
  'RotateCcw',
  'ReceiptText',
];
const brands = {
  whatsapp: 'siWhatsapp',
  instagram: 'siInstagram',
  facebook: 'siFacebook',
  youtube: 'siYoutube',
};

const kebab = (s) =>
  s
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Za-z])(\d)/g, '$1-$2')
    .toLowerCase();
const nodeToSvg = (nodes) =>
  nodes
    .map(
      ([tag, attrs]) =>
        `<${tag} ${Object.entries(attrs)
          .map(([k, v]) => `${k}="${v}"`)
          .join(' ')}/>`,
    )
    .join('');

const out = {};
for (const name of stroke) {
  const node = lucide[name];
  if (!node) throw new Error(`Lucide icon not found: ${name}`);
  out[kebab(name)] = { kind: 'stroke', body: nodeToSvg(node) };
}
for (const [key, exportName] of Object.entries(brands)) {
  const icon = simple[exportName];
  if (!icon) throw new Error(`Simple Icons mark not found: ${exportName}`);
  out[key] = { kind: 'fill', body: `<path d="${icon.path}"/>` };
}

const file = `/**
 * Icon registry, generated by scripts/build-icons.mjs. Do not edit by hand.
 * Stroke icons: Lucide (ISC licence). Brand marks: Simple Icons (CC0).
 */
export interface IconDef {
  kind: 'stroke' | 'fill';
  body: string;
}

export const icons = ${JSON.stringify(out, null, 2)} as const satisfies Record<string, IconDef>;

export type IconName = keyof typeof icons;
`;
writeFileSync(new URL('../src/lib/icons.ts', import.meta.url), file);
console.log(`Wrote ${Object.keys(out).length} icons to src/lib/icons.ts`);
