/**
 * Downloads the demo photos listed in scripts/photos/manifest.json into
 * src/assets/images/ and rewrites CREDITS.md.
 *
 *   npm run photos:fetch            only files that are missing
 *   npm run photos:fetch -- --force re-download everything
 *
 * Photos come from Unsplash (Unsplash License: free to use, no permission
 * needed). Each is cropped to its slot's size around an optional focus
 * point; gallery photos keep their own shape for the masonry grid.
 * Behind a proxy on Node 22, run with NODE_USE_ENV_PROXY=1.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '../..');
const manifest = JSON.parse(readFileSync(join(root, 'scripts/photos/manifest.json'), 'utf8'));
const force = process.argv.includes('--force');
const imagesDir = join(root, 'src/assets/images');

function sourceUrl(entry) {
  const params = new URLSearchParams({ fm: 'jpg', q: '82' });
  if (entry.size.longEdge) {
    params.set('w', String(entry.size.longEdge));
    params.set('h', String(entry.size.longEdge));
    params.set('fit', 'max');
  } else {
    params.set('w', String(entry.size.width));
    params.set('h', String(entry.size.height));
    params.set('fit', 'crop');
    const [x = '0.5', y = '0.5'] = (entry.size.focus ?? '').split(',').filter(Boolean);
    params.set('crop', 'focalpoint');
    params.set('fp-x', x);
    params.set('fp-y', y);
  }
  return `${entry.url}?${params}`;
}

let fetched = 0;
for (const entry of manifest) {
  const target = join(imagesDir, entry.slot);
  if (!force && existsSync(target)) continue;
  const res = await fetch(sourceUrl(entry));
  if (!res.ok) throw new Error(`${entry.slot}: HTTP ${res.status}`);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, Buffer.from(await res.arrayBuffer()));
  fetched += 1;
  console.log(`✓ ${entry.slot}`);
}

// CREDITS.md: every photo, its photographer and a link back.
const utm = 'utm_source=butter_and_bloom_demo&utm_medium=referral';
const groups = new Map();
for (const entry of manifest) {
  const group = entry.slot.split('/')[0];
  if (!groups.has(group)) groups.set(group, []);
  groups.get(group).push(entry);
}
const titles = {
  hero: 'Home hero',
  story: 'Home story',
  occasions: 'Occasion tiles',
  misc: 'Other pages',
  about: 'About page',
  menu: 'Menu',
  gallery: 'Gallery',
};
const lines = [
  '# Photo credits',
  '',
  'The demo photos are from [Unsplash](https://unsplash.com/?' +
    utm +
    ') and used under the [Unsplash License](https://unsplash.com/license): free to use, including commercially, with no permission needed. Credit is not required but is given here with thanks.',
  '',
  'They are stand-ins for the demo. For a client site, replace them with photographs of the bakery’s own products (see REBRAND.md): real photos of real bakes sell better and avoid any look-alike claims.',
  '',
  'Regenerated by `npm run photos:fetch` from `scripts/photos/manifest.json`.',
  '',
];
for (const [group, entries] of groups) {
  lines.push(
    `## ${titles[group] ?? group}`,
    '',
    '| File | Photo | Photographer |',
    '| --- | --- | --- |',
  );
  for (const e of entries) {
    lines.push(
      `| \`${e.slot}\` | [Unsplash ${e.id}](${e.page}?${utm}) | [${e.photographer}](https://unsplash.com/@${e.username}?${utm}) |`,
    );
  }
  lines.push('');
}
writeFileSync(join(root, 'CREDITS.md'), lines.join('\n'));
console.log(`\n${fetched} photo(s) downloaded · CREDITS.md updated (${manifest.length} photos)`);
