/**
 * Every photo slot the site uses, relative to src/assets/images/.
 * w × h is the size to supply (or larger, same aspect ratio).
 * `query` is the search used to curate the demo photo; `subject` describes
 * what a client should photograph to replace it.
 */
const menu = [
  ['belgian-chocolate-truffle', 'chocolate truffle cake ganache', 'Whole chocolate truffle cake'],
  [
    'red-velvet-cream-cheese',
    'red velvet cake slice',
    'Red velvet cake with cream cheese frosting',
  ],
  ['salted-caramel-butterscotch', 'caramel cake drip', 'Caramel butterscotch cake'],
  ['rasmalai-fusion-cake', 'pistachio saffron cake', 'Rasmalai cake with pistachio'],
  ['fresh-mango-cream', 'mango cream cake', 'Mango fresh cream cake'],
  ['pistachio-rose', 'pistachio rose cake', 'Pistachio rose cake with petals'],
  ['lotus-biscoff', 'biscoff cake', 'Biscoff caramel cake'],
  ['baked-blueberry-cheesecake', 'blueberry cheesecake', 'Baked blueberry cheesecake'],
  ['chocolate-truffle-pastry', 'chocolate pastry slice', 'Chocolate truffle pastry slice'],
  ['red-velvet-pastry', 'red velvet pastry', 'Red velvet pastry slice'],
  ['pineapple-fresh-cream-pastry', 'fresh cream pastry', 'Pineapple fresh cream pastry'],
  ['biscoff-cheesecake-slice', 'cheesecake slice caramel', 'Biscoff cheesecake slice'],
  ['tiramisu-cup', 'tiramisu glass', 'Tiramisu in a cup'],
  ['rasmalai-tres-leches', 'tres leches cake', 'Tres leches slice'],
  ['fudge-brownie', 'fudge brownie', 'Fudge brownies'],
  ['nutella-brownie', 'nutella brownie', 'Nutella brownie'],
  ['double-chocolate-cookies', 'double chocolate cookies', 'Double chocolate cookies'],
  ['millet-jaggery-cookies', 'oat cookies rustic', 'Millet jaggery cookies'],
  ['banana-walnut-tea-cake', 'banana bread walnut', 'Banana walnut loaf'],
  ['butter-tea-biscuits', 'butter biscuits tea', 'Butter biscuits'],
  ['butter-croissant', 'butter croissant', 'Butter croissants'],
  ['almond-croissant', 'almond croissant', 'Almond croissant'],
  ['multigrain-sourdough-loaf', 'sourdough loaf seeds', 'Multigrain sourdough loaf'],
  ['soft-milk-bread', 'milk bread loaf', 'Soft milk bread'],
  ['garlic-cheese-pull-apart', 'garlic cheese pull apart bread', 'Garlic cheese pull-apart bread'],
  ['classic-veg-puff', 'puff pastry', 'Veg puffs'],
  ['paneer-tikka-puff', 'savoury puff pastry', 'Paneer puff'],
  ['egg-puff', 'egg puff pastry', 'Egg puff'],
  ['chicken-keema-puff', 'meat puff pastry', 'Chicken puff'],
  ['paneer-tikka-sandwich', 'grilled sandwich', 'Paneer tikka sandwich'],
  ['chicken-pesto-croissant-sandwich', 'croissant sandwich', 'Chicken croissant sandwich'],
  ['classic-cold-coffee', 'iced coffee glass', 'Cold coffee'],
  ['belgian-hot-chocolate', 'hot chocolate mug', 'Hot chocolate'],
  ['masala-chai', 'masala chai', 'Masala chai'],
  ['lime-mint-cooler', 'lime mint drink', 'Lime mint cooler'],
].map(([id, query, subject]) => ({ path: `menu/${id}.jpg`, w: 1200, h: 1200, query, subject }));

const gallery = [
  ['birthday-01', 'birthday cake candles', 'Birthday cake', 1200, 1500],
  ['birthday-02', 'chocolate drip cake', 'Birthday drip cake', 1200, 1200],
  ['birthday-03', 'birthday cake sprinkles', 'Birthday cake with sprinkles', 1200, 1600],
  ['birthday-04', 'cake celebration table', 'Birthday table', 1600, 1200],
  ['anniversary-01', 'elegant white cake flowers', 'Anniversary cake', 1200, 1500],
  ['anniversary-02', 'heart cake', 'Heart cake', 1200, 1200],
  ['anniversary-03', 'cake roses', 'Cake with roses', 1600, 1200],
  ['wedding-01', 'wedding cake tiers', 'Tiered wedding cake', 1200, 1700],
  ['wedding-02', 'wedding cake flowers', 'Wedding cake with flowers', 1200, 1500],
  ['wedding-03', 'naked cake flowers', 'Semi-naked cake', 1200, 1200],
  ['wedding-04', 'engagement cake', 'Engagement cake', 1600, 1200],
  ['kids-01', 'colourful kids cake', 'Kids cake', 1200, 1500],
  ['kids-02', 'rainbow cake', 'Rainbow cake', 1200, 1200],
  ['kids-03', 'cupcakes colourful', 'Cupcakes', 1600, 1200],
  ['festive-01', 'gift box sweets', 'Festive hamper', 1200, 1500],
  ['festive-02', 'cookies gift box', 'Cookie gift box', 1200, 1200],
  ['festive-03', 'diwali lights sweets', 'Festive table', 1600, 1200],
  ['festive-04', 'christmas cookies', 'Festive cookies', 1200, 1500],
  ['corporate-01', 'gift boxes ribbon', 'Corporate gift boxes', 1200, 1500],
  ['corporate-02', 'macarons box', 'Macaron box', 1600, 1200],
  ['corporate-03', 'dessert table event', 'Dessert table', 1200, 1200],
].map(([id, query, subject, w, h]) => ({ path: `gallery/${id}.jpg`, w, h, query, subject }));

const pages = [
  [
    'hero/hero.jpg',
    2400,
    1600,
    'celebration cake cake stand',
    'Hero: a tall celebration cake, warm light',
  ],
  [
    'hero/hero-mobile.jpg',
    1200,
    1800,
    'celebration cake cake stand vertical',
    'Hero (portrait crop for phones)',
  ],
  ['story/story-1.jpg', 1200, 1600, 'baker hands dough', 'Story: hands shaping dough'],
  ['story/story-2.jpg', 1200, 1200, 'croissants tray', 'Story: tray of croissants'],
  ['occasions/birthday.jpg', 1200, 1500, 'birthday cake', 'Occasion tile: birthday'],
  ['occasions/anniversary.jpg', 1200, 1500, 'anniversary cake', 'Occasion tile: anniversary'],
  ['occasions/wedding.jpg', 1200, 1500, 'wedding cake', 'Occasion tile: wedding & engagement'],
  ['occasions/kids.jpg', 1200, 1500, 'kids birthday cake', "Occasion tile: kids' theme"],
  ['occasions/festive.jpg', 1200, 1500, 'festive gift hamper', 'Occasion tile: festive hampers'],
  ['occasions/corporate.jpg', 1200, 1500, 'gift boxes', 'Occasion tile: corporate gifting'],
  [
    'misc/builder-teaser.jpg',
    1600,
    1200,
    'piping cream cake decorating',
    'Cake builder teaser: decorating a cake',
  ],
  ['about/about-hero.jpg', 2000, 1300, 'bakery counter pastries', 'About: the counter'],
  ['about/strip-1.jpg', 1200, 1500, 'baker kneading dough', 'Behind the counter 1'],
  ['about/strip-2.jpg', 1200, 1500, 'piping cream', 'Behind the counter 2'],
  ['about/strip-3.jpg', 1200, 1500, 'oven bread', 'Behind the counter 3'],
  ['about/strip-4.jpg', 1200, 1500, 'flour baking', 'Behind the counter 4'],
  ['about/hands.jpg', 1200, 1500, 'baker hands flour', 'Founder card: hands only, no face'],
  ['misc/corporate.jpg', 1600, 1200, 'gift boxes ribbon', 'Corporate & bulk orders'],
  ['misc/not-found.jpg', 1200, 1200, 'crumbs croissant', '404 page'],
].map(([path, w, h, query, subject]) => ({ path, w, h, query, subject }));

export const slots = [...pages, ...menu, ...gallery];
